# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16o-qqrRMJZm9IJB8dm3rvsPjmQ9P5FWI
"""

# ---- Install & Import ----
!pip install opencv-python matplotlib

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ---- Read Original Color Image ----
img = cv2.imread("sample.jpg")   # Reads in BGR
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
img = cv2.resize(img,(400,400))

# ---- 1. Contrast Stretching (Min-Max Normalization) ----
min_val = np.min(img)
max_val = np.max(img)
cs1 = ((img - min_val) / (max_val - min_val) * 255).astype(np.uint8)

# ---- 2. Contrast Stretching (Piecewise Linear) ----
r1, s1 = 50, 0
r2, s2 = 200, 255

def piecewise_linear(x):
    if x < r1:
        return (s1/r1)*x
    elif x < r2:
        return ((s2-s1)/(r2-r1))*(x-r1) + s1
    else:
        return ((255-s2)/(255-r2))*(x-r2) + s2

cs2 = np.zeros_like(img)
for c in range(3):  # apply on each color channel
    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            cs2[i,j,c] = piecewise_linear(img[i,j,c])
cs2 = cs2.astype(np.uint8)

# ---- 3. Log Transformation ----
c = 255 / np.log(1 + np.max(img))
log_img = (c * np.log(1 + img)).astype(np.uint8)

# ---- 4. Power-Law (Gamma) Transformation ----
gamma = 0.5  # try 0.3, 1.5 etc
pl_img = np.array(255*(img/255)**gamma, dtype=np.uint8)

# ---- Display Results ----
titles = ['Original','Contrast Stretch 1','Contrast Stretch 2','Log Transform','Gamma Transform']
images = [img, cs1, cs2, log_img, pl_img]

plt.figure(figsize=(15,8))
for i in range(5):
    plt.subplot(2,3,i+1)
    plt.imshow(images[i])
    plt.title(titles[i])
    plt.axis('off')
plt.show()