# -*- coding: utf-8 -*-
"""Lab9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhmAWNbdCYB6J_7pqWwoFqCLum0a68I5
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load image in grayscale (update the path as needed)
img = cv2.imread('download.jpg', cv2.IMREAD_GRAYSCALE)

# Show original image
plt.imshow(img, cmap='gray')
plt.title('Original')
plt.axis('off')
plt.show()

# Define high-pass filter (sharpen kernel)
hp_kernel = np.array([[-1, -1, -1],
                      [-1,  8, -1],
                      [-1, -1, -1]])

high_pass_result = cv2.filter2D(img, -1, hp_kernel)

# Show high-pass filter result
plt.imshow(high_pass_result, cmap='gray')
plt.title('High Pass Filter')
plt.axis('off')
plt.show()

A = 1.5  # High boost factor (>1)
blur = cv2.GaussianBlur(img, (3,3), 0)
high_boost_result = cv2.addWeighted(img, A, blur, (1-A), 0)

# Show high-boost filter result
plt.imshow(high_boost_result, cmap='gray')
plt.title('High Boost Filter')
plt.axis('off')
plt.show()

prewitt_x = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
prewitt_y = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])

prewitt_x_result = cv2.filter2D(img, -1, prewitt_x)
prewitt_y_result = cv2.filter2D(img, -1, prewitt_y)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(prewitt_x_result, cmap='gray')
plt.title('Prewitt X')
plt.axis('off')
plt.subplot(1,2,2)
plt.imshow(prewitt_y_result, cmap='gray')
plt.title('Prewitt Y')
plt.axis('off')
plt.show()

sobel_x_result = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
sobel_y_result = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(np.abs(sobel_x_result), cmap='gray')
plt.title('Sobel X')
plt.axis('off')
plt.subplot(1,2,2)
plt.imshow(np.abs(sobel_y_result), cmap='gray')
plt.title('Sobel Y')
plt.axis('off')
plt.show()

roberts_cross_v = np.array([[1, 0], [0, -1]])
roberts_cross_h = np.array([[0, 1], [-1, 0]])

roberts_v_result = cv2.filter2D(img, -1, roberts_cross_v)
roberts_h_result = cv2.filter2D(img, -1, roberts_cross_h)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(roberts_v_result, cmap='gray')
plt.title('Roberts Vertical')
plt.axis('off')
plt.subplot(1,2,2)
plt.imshow(roberts_h_result, cmap='gray')
plt.title('Roberts Horizontal')
plt.axis('off')
plt.show()

laplacian_result = cv2.Laplacian(img, cv2.CV_64F, ksize=3)

plt.imshow(np.abs(laplacian_result), cmap='gray')
plt.title('Laplacian')
plt.axis('off')
plt.show()