# -*- coding: utf-8 -*-
"""Lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIGqEsjQPVQUCr1V7tX-U1VM_AdItv75
"""

# Run this in Google Colab

import cv2
from matplotlib import pyplot as plt
import numpy as np

# Upload files tool
from google.colab import files

print("Please upload your 4 images (bright, dark, low contrast, high contrast)")
uploaded = files.upload()

# The uploaded dict keys are filenames, we will read each one
# Convert to grayscale for histogram and equalization

images = {}
for filename in uploaded.keys():
    img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)  # Read grayscale directly
    images[filename] = img

# Function to plot image and histogram side by side
def plot_image_and_histogram(img, title):
    plt.figure(figsize=(10,4))
    plt.subplot(1,2,1)
    plt.imshow(img, cmap='gray')
    plt.title(title)
    plt.axis('off')

    plt.subplot(1,2,2)
    plt.hist(img.ravel(), bins=256, range=(0,255), color='black')
    plt.title('Histogram')
    plt.xlabel('Pixel Intensity')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

print("Original Images and Histograms")
for name, img in images.items():
    plot_image_and_histogram(img, f"{name} - Original")

# Now Histogram Equalization
print("Histogram Equalization Results")
for name, img in images.items():
    equalized_img = cv2.equalizeHist(img)
    plot_image_and_histogram(equalized_img, f"{name} - Equalized")