# -*- coding: utf-8 -*-
"""lab8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-FNhUikmocyyDsHcEWVsxdlT5jpSICvV
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Upload and load image as grayscale
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]
img_bgr = cv2.imread(filename)
img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
img = np.array(img_gray, dtype=np.uint8)

# Pad image for border processing
def pad_image(image, ksize):
    pad = ksize // 2
    return np.pad(image, ((pad, pad), (pad, pad)), mode='edge')

# 1. Lowpass (mean) filter
def mean_filter(image, ksize=3):
    padded = pad_image(image, ksize)
    out = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            roi = padded[i:i+ksize, j:j+ksize]
            out[i, j] = np.mean(roi)
    return np.uint8(out)

# 2. Median filter
def median_filter(image, ksize=3):
    padded = pad_image(image, ksize)
    out = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            roi = padded[i:i+ksize, j:j+ksize]
            out[i, j] = np.median(roi)
    return np.uint8(out)

# 3. Max filter
def max_filter(image, ksize=3):
    padded = pad_image(image, ksize)
    out = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            roi = padded[i:i+ksize, j:j+ksize]
            out[i, j] = np.max(roi)
    return np.uint8(out)

# 4. Min filter
def min_filter(image, ksize=3):
    padded = pad_image(image, ksize)
    out = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            roi = padded[i:i+ksize, j:j+ksize]
            out[i, j] = np.min(roi)
    return np.uint8(out)

# 5. Midpoint filter
def midpoint_filter(image, ksize=3):
    padded = pad_image(image, ksize)
    out = np.zeros_like(image)
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            roi = padded[i:i+ksize, j:j+ksize]
            out[i, j] = 0.5 * (np.max(roi) + np.min(roi))
    return np.uint8(out)

# --- Filtering results ---
mean_img = mean_filter(img, 3)
median_img = median_filter(img, 3)
max_img = max_filter(img, 3)
min_img = min_filter(img, 3)
midpoint_img = midpoint_filter(img, 3)

# --- Plotting results ---
titles = ['Original', 'Mean (Lowpass)', 'Median', 'Max', 'Min', 'Midpoint']
images = [img, mean_img, median_img, max_img, min_img, midpoint_img]

plt.figure(figsize=(15,8))
for i in range(6):
    plt.subplot(2, 3, i+1)
    plt.imshow(images[i], cmap='gray')
    plt.title(titles[i])
    plt.axis('off')
plt.show()