# -*- coding: utf-8 -*-
"""Lab11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGQnJokJo4Jh5CVdOCyBLcYlKJiICZJe
"""

# Cell 1: Install (if needed) and imports
!pip install opencv-python scikit-image -q

import cv2
import numpy as np
from matplotlib import pyplot as plt
from skimage.morphology import skeletonize, thin, convex_hull_image  # for skeleton, thinning, convex hull

print("Libraries imported.")

# Cell 2: Read image and convert to binary
# Replace the path with your own image or upload and use that filename
img = cv2.imread("input.webp", 0)   # 0 = grayscale

# Threshold to get a binary image (foreground = white, background = black)
_, binary = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

plt.figure(figsize=(4,4))
plt.imshow(binary, cmap='gray')
plt.title("Original Binary")
plt.axis('off')

# Cell 3: Define structuring element (kernel)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
print(kernel)

# Cell 4: Dilation
dilated = cv2.dilate(binary, kernel, iterations=1)  # expands white regions [web:1][web:5]

plt.figure(figsize=(4,4))
plt.imshow(dilated, cmap='gray')
plt.title("Dilation")
plt.axis('off')

# Cell 5: Erosion
eroded = cv2.erode(binary, kernel, iterations=1)  # shrinks white regions [web:1][web:5]

plt.figure(figsize=(4,4))
plt.imshow(eroded, cmap='gray')
plt.title("Erosion")
plt.axis('off')

# Cell 6: Opening (erosion then dilation)
opened = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)  # removes small objects / noise [web:2][web:8][web:14]

plt.figure(figsize=(4,4))
plt.imshow(opened, cmap='gray')
plt.title("Opening")
plt.axis('off')

# Cell 7: Closing (dilation then erosion)
closed = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)  # fills small holes and gaps [web:3][web:8]

plt.figure(figsize=(4,4))
plt.imshow(closed, cmap='gray')
plt.title("Closing")
plt.axis('off')

# Cell 8: Boundary detection (outer boundary of objects)
# One simple way: boundary = dilation - original or original - erosion
boundary = cv2.morphologyEx(binary, cv2.MORPH_GRADIENT, kernel)  # gradient = dilation - erosion [web:5][web:18]

plt.figure(figsize=(4,4))
plt.imshow(boundary, cmap='gray')
plt.title("Boundary")
plt.axis('off')

# Cell 9: Region filling (fill holes inside objects)
# Use flood fill from a background point, then invert and combine

# Make a copy and a mask
im_floodfill = binary.copy()
h, w = binary.shape[:2]
mask = np.zeros((h+2, w+2), np.uint8)

# Flood fill from (0, 0)
cv2.floodFill(im_floodfill, mask, (0, 0), 255)

# Invert floodfilled image
im_floodfill_inv = cv2.bitwise_not(im_floodfill)

# Combine original and inverted floodfilled image to fill holes
filled = binary | im_floodfill_inv  # region filling result [web:13][web:18]

plt.figure(figsize=(4,4))
plt.imshow(filled, cmap='gray')
plt.title("Region Filling")
plt.axis('off')

# Cell 10: Thinning (reduce foreground to single-pixel wide lines)
# skimage thin expects boolean image
binary_bool = (binary > 0)

thinned = thin(binary_bool)  # morphological thinning [web:12][web:20]

thinned_img = (thinned * 255).astype(np.uint8)

plt.figure(figsize=(4,4))
plt.imshow(thinned_img, cmap='gray')
plt.title("Thinning")
plt.axis('off')

# Cell 11: Skeletonization (topological skeleton)
skeleton = skeletonize(binary_bool)  # skeleton of shapes [web:20]

skeleton_img = (skeleton * 255).astype(np.uint8)

plt.figure(figsize=(4,4))
plt.imshow(skeleton_img, cmap='gray')
plt.title("Skeleton")
plt.axis('off')

# Cell 12: Thickening (approximate via dilating a thinned/skeleton image)
# True thickening is dual to thinning, but OpenCV has no direct function, so this is an illustration [web:15]

thickened = cv2.dilate(thinned_img, kernel, iterations=1)

plt.figure(figsize=(4,4))
plt.imshow(thickened, cmap='gray')
plt.title("Thickening (approx.)")
plt.axis('off')

# Cell 13: Convex hull of binary object
# Use skimage convex_hull_image for a simple binary convex hull [web:7][web:10]

convex = convex_hull_image(binary_bool)
convex_img = (convex * 255).astype(np.uint8)

plt.figure(figsize=(4,4))
plt.imshow(convex_img, cmap='gray')
plt.title("Convex Hull")
plt.axis('off')

# Cell 14: Show all results in a grid (optional)

titles = [
    "Binary", "Dilation", "Erosion",
    "Opening", "Closing", "Boundary",
    "Filled", "Thinning", "Skeleton",
    "Thickening", "Convex Hull"
]

images = [
    binary, dilated, eroded,
    opened, closed, boundary,
    filled, thinned_img, skeleton_img,
    thickened, convex_img
]

plt.figure(figsize=(12,10))
for i, (img_show, title) in enumerate(zip(images, titles)):
    plt.subplot(3, 4, i+1)
    plt.imshow(img_show, cmap='gray')
    plt.title(title)
    plt.axis('off')

plt.tight_layout()